version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:16-bookworm
    restart: always
    environment:
      POSTGRES_USER: usuario # Nome do usuario root
      POSTGRES_PASSWORD: '1234' # Senha do usuario root
      POSTGRES_DB: banco # Nome do banco de dados.
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  data: