version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:16-bookworm
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: teste
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  data: